### ISSUE TITLE
String not recognized as a valid boolean

### ISSUE THREAD

**Issue by Ryrynz** [Garteal/MPDN_Extensions#25] opened 2015-08-05 02:10 UTC
Since doom9 sucks and I can't PM, try enabling Scale with player on your latest dev build.

**Comment by Ryrynz** [comment] 2015-08-05 02:12
BTW at least on 7 and 10 the snapping is fine, can test 8 later today.

**Comment by zachsaw** [comment] 2015-08-06 00:06
I enabled scale with player - no issues here...

**Comment by Garteal** [comment] 2015-09-17 15:40
Closing because I too couldn't reproduce.

**Closed as completed by Garteal** 2015-09-17 15:40 UTC
